services:
  kafka:
    image: bitnami/kafka:3.4
    ports:
      - "9092:9092"
    environment:
      # General config
      ALLOW_PLAINTEXT_LISTENER: "yes"
      # KRaft mode configuration
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CFG_NODE_ID: "1"
      # Clustering
      KAFKA_CFG_NUM_PARTITIONS: 2
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 1
    networks:
      - kafka-network
    volumes:
      - kafka_data:/bitnami/kafka

  producer:
    build: ./producer
    depends_on:
      - kafka
    networks:
      - kafka-network
    ports:
      - "3000:3000"

  consumer:
    build: ./consumer
    depends_on:
      - kafka
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge

volumes:
  kafka_data:
    driver: local
